name: terraform-apply
{% raw %}
on:
  issue_comment:
    types: [created]

jobs:

  terraform-apply-dev:
    # Only run for comments starting with "terraform apply dev" in a pull request.
    if: >
      startsWith(github.event.comment.body, 'terraform apply dev')
      && startsWith(github.event.issue.pull_request.url, 'https://')
  
    name: terraform-apply-dev
    runs-on: ubuntu-latest

    env:
      WORKSPACE: 'dev'
      AWS_REGION: 'us-east-1'
      IAM_ROLE_SESSION_NAME: "gha-terraform-dev"
      #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_K_ID_DEV }}
      #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S_ID_DEV }}
    
    permissions:
      id-token: write
      contents: read
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Load PR Details'
        id: load-pr
        run: |
          set -eu
          echo ${{ github.event.issue.pull_request.url }}
          echo ${{ secrets.CROSS_REPO_TOKEN }}
          resp=$(curl -sSf \
            --url ${{ github.event.issue.pull_request.url }} \
            --header 'Authorization: Bearer ${{ secrets.CROSS_REPO_TOKEN }}' \
            --header 'Accept: application/vnd.github+json')
          sha=$(jq -r '.head.sha' <<< "$resp")
          echo "head_sha=$sha" >> $GITHUB_OUTPUT
          comments_url=$(jq -r '.comments_url' <<< "$resp")
          echo "comments_url=$comments_url" >> $GITHUB_OUTPUT
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # By default (in a non-pull request build) you get HEAD of 'master'
          ref: ${{ steps.load-pr.outputs.head_sha }}
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }} # Needed for private submodules
      
      - name: Get Federated OIDC IAM Role For Environment
        id: iam-role
        run: |
          OIDC=$( cat environments/dev/oidc-iam-role.txt )
          echo $OIDC
          echo "iam_role=$OIDC" >> $GITHUB_OUTPUT
      
      - name: Build Workspace / Environment
        id: build-environment
        env:
          OK_ENV: 'dev'
        run: |
          cd environments/$OK_ENV
          make
          ls -la
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ steps.iam-role.outputs.iam_role }}
          role-session-name: ${{ env.IAM_ROLE_SESSION_NAME }}

      - name: Setup AWSCli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64
      
      - name: Setup Terraform
        id: terraform-setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3
          terraform_wrapper: false
      
      - name: terraform init
        id: terraform-init
        env:
          OK_ENV: 'dev'
        run: terraform -chdir=environments/$OK_ENV init
      
      - name: terraform format
        id: terraform-format
        env:
          OK_ENV: 'dev'
        run: terraform -chdir=environments/$OK_ENV fmt -check -diff
      
      - name: terraform validate
        id: terraform-validate
        env:
          OK_ENV: 'dev'
        run: terraform -chdir=environments/$OK_ENV validate
      
      - name: terraform plan
        id: terraform-plan
        env:
          OK_ENV: 'dev'
        run: |
          set -eu
          cat environments/$OK_ENV/terraform.tfvars
          terraform -chdir=environments/$OK_ENV plan -out tfplan.binary
          terraform_plan_out=$(terraform -chdir=environments/$OK_ENV plan -out tfplan.binary)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "tf_plan_out<<$EOF" >> $GITHUB_OUTPUT
          echo "$terraform_plan_out" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      
      - name: Convert Terraform Plan To JSON
        id: terraform-json
        env:
          OK_ENV: 'dev'
        run: terraform -chdir=environments/$OK_ENV show -json tfplan.binary | jq -r '.' > tfplan.json
      
      - name: Install PIP3
        id: install-pip3
        run: |
          sudo apt-get -y install python3-pip
      
      - name: Install Checkov
        id: install-checkov
        env:
          OK_ENV: 'dev'
        run: pip3 install checkov
      
      - name: Static Code Security Analysis
        id: run-checkov
        run: checkov -f tfplan.json -s --quiet
      
      - name: terraform apply
        id: terraform-apply
        env:
          OK_ENV: 'dev'
        run: |
          set -eu
          terraform -chdir=environments/$OK_ENV apply tfplan.binary
{% endraw %}
